### ISSUE TITLE
Add VMs images

### ISSUE THREAD

**Issue by Igorgro** [upmaru/opsmaru-images#6]
For now there are only container images, but LXD is able to run VMs too

**Comment by zacksiri** [comment]
This is now done. All the configuration is in place and the following now have VM images

- all alpine versions
- all ubuntu versions
- debian bookworm

sid is the only pending one now due to some issue with the build. I've already submitted a patch here https://github.com/lxc/distrobuilder/pull/826

Which should resolve the issue with sid.

**Comment by Igorgro** [comment]
Do this images contain lxd/incus agent? Because if there is no cloud-init, so there is no way to create user and install ssh server

**Comment by zacksiri** [comment]
@Igorgro the cloud-init version is coming. 

The sid version is broken from the upstream there is a bug https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1958237.html

**Comment by Igorgro** [comment]
@zacksiri if there is no cloud-init, it's also ok, but is there incus/lxd installed in image, so I can get into shell and create user and install ssh server?

**Comment by zacksiri** [comment]
The image is the same as what was in the community server. You should be able to get into shell.

**Comment by zacksiri** [comment]
I'm closing this issue since the VM is now done.
